addons:
  apt:
    packages:
      - docker-ce

language: generic

sudo: required

services:
  - docker

script:
  - make build/dev
  - make args="./bin/test.sh" run/dev
  - make build/service
  - make args="-- https://httpbin.org/html -" run/cli | grep -a "PDF-1.4"

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" -o "$TRAVIS_BRANCH" != "master" -o -n "$TRAVIS_TAG" ]; then exit 0; fi
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push arachnysdocker/athenapdf
  - docker push arachnysdocker/athenapdf-service
